os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8.3

install:
  - curl -L https://rawgit.com/noppoMan/swift-scripts/master/install-swift3.sh > install-swift3.sh
  - source ./install-swift3.sh

script:
  - swift build
  - swift build -c release
